/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.njk","./src/**/*.md","./src/**/*.html"],
  theme: {
    extend: {
      colors: {
        /* All colors reference CSS variables so dark mode works via .dark class */
        "primary":                    "var(--c-primary)",
        "primary-container":          "var(--c-primary-container)",
        "primary-fixed":              "var(--c-primary-fixed)",
        "primary-fixed-dim":          "var(--c-primary-fixed-dim)",
        "on-primary":                 "var(--c-on-primary)",
        "on-primary-container":       "var(--c-on-primary-container)",
        "on-primary-fixed":           "var(--c-on-primary-fixed)",
        "on-primary-fixed-variant":   "var(--c-on-primary-fixed-variant)",
        "inverse-primary":            "var(--c-inverse-primary)",
        "secondary":                  "var(--c-secondary)",
        "secondary-container":        "var(--c-secondary-container)",
        "secondary-fixed":            "var(--c-secondary-fixed)",
        "secondary-fixed-dim":        "var(--c-secondary-fixed-dim)",
        "on-secondary":               "var(--c-on-secondary)",
        "on-secondary-container":     "var(--c-on-secondary-container)",
        "on-secondary-fixed":         "var(--c-on-secondary-fixed)",
        "on-secondary-fixed-variant": "var(--c-on-secondary-fixed-variant)",
        "tertiary":                   "var(--c-tertiary)",
        "tertiary-container":         "var(--c-tertiary-container)",
        "tertiary-fixed":             "var(--c-tertiary-fixed)",
        "tertiary-fixed-dim":         "var(--c-tertiary-fixed-dim)",
        "on-tertiary":                "var(--c-on-tertiary)",
        "on-tertiary-container":      "var(--c-on-tertiary-container)",
        "on-tertiary-fixed":          "var(--c-on-tertiary-fixed)",
        "on-tertiary-fixed-variant":  "var(--c-on-tertiary-fixed-variant)",
        "error":                      "var(--c-error)",
        "error-container":            "var(--c-error-container)",
        "on-error":                   "var(--c-on-error)",
        "on-error-container":         "var(--c-on-error-container)",
        "surface":                    "var(--c-surface)",
        "surface-dim":                "var(--c-surface-dim)",
        "surface-bright":             "var(--c-surface-bright)",
        "surface-variant":            "var(--c-surface-variant)",
        "surface-tint":               "var(--c-surface-tint)",
        "surface-container":          "var(--c-surface-container)",
        "surface-container-lowest":   "var(--c-surface-container-lowest)",
        "surface-container-low":      "var(--c-surface-container-low)",
        "surface-container-high":     "var(--c-surface-container-high)",
        "surface-container-highest":  "var(--c-surface-container-highest)",
        "on-surface":                 "var(--c-on-surface)",
        "on-surface-variant":         "var(--c-on-surface-variant)",
        "on-background":              "var(--c-on-background)",
        "background":                 "var(--c-background)",
        "outline":                    "var(--c-outline)",
        "outline-variant":            "var(--c-outline-variant)",
        "inverse-surface":            "var(--c-inverse-surface)",
        "inverse-on-surface":         "var(--c-inverse-on-surface)",
      },
      borderRadius: { DEFAULT:"0.25rem", lg:"0.5rem", xl:"0.75rem", full:"9999px" },
      fontFamily: {
        "body-sm":            ["Inter","system-ui","sans-serif"],
        "body-lead":          ["Inter","system-ui","sans-serif"],
        "body-default":       ["Inter","system-ui","sans-serif"],
        "headline-sm":        ["Manrope","system-ui","sans-serif"],
        "headline-md":        ["Manrope","system-ui","sans-serif"],
        "headline-lg":        ["Manrope","system-ui","sans-serif"],
        "headline-xl":        ["Manrope","system-ui","sans-serif"],
        "display-hero":       ["Manrope","system-ui","sans-serif"],
        "display-hero-mobile":["Manrope","system-ui","sans-serif"],
        "label-md":           ["Inter","system-ui","sans-serif"],
        "label-xs":           ["Inter","system-ui","sans-serif"],
      },
      fontSize: {
        "body-sm":            ["14px",{lineHeight:"22px",fontWeight:"400"}],
        "body-lead":          ["18px",{lineHeight:"29px",fontWeight:"400"}],
        "body-default":       ["16px",{lineHeight:"26px",fontWeight:"400"}],
        "headline-sm":        ["16px",{lineHeight:"22px",letterSpacing:"-0.01em",fontWeight:"600"}],
        "headline-md":        ["19px",{lineHeight:"26px",letterSpacing:"-0.015em",fontWeight:"600"}],
        "headline-lg":        ["24px",{lineHeight:"32px",letterSpacing:"-0.02em",fontWeight:"700"}],
        "headline-xl":        ["36px",{lineHeight:"44px",letterSpacing:"-0.025em",fontWeight:"700"}],
        "display-hero":       ["48px",{lineHeight:"56px",letterSpacing:"-0.03em",fontWeight:"800"}],
        "display-hero-mobile":["32px",{lineHeight:"40px",letterSpacing:"-0.02em",fontWeight:"800"}],
        "headline-xl-mobile": ["26px",{lineHeight:"34px",letterSpacing:"-0.02em",fontWeight:"700"}],
        "label-md":           ["13px",{lineHeight:"16px",letterSpacing:"0.01em",fontWeight:"600"}],
        "label-xs":           ["11px",{lineHeight:"14px",letterSpacing:"0.05em",fontWeight:"700"}],
      }
    }
  },
  plugins: []
}
